// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtsjltutcoovebimrosr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0c2psdHV0Y29vdmViaW1yb3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDc4MzYsImV4cCI6MjA2MDIyMzgzNn0.L3kO-rNkw7hYOyC722t_QHQsdESknJqYLtTHcllWKGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);