// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzmtjhrokilijrzwqgdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6bXRqaHJva2lsaWpyendxZ2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzExODgsImV4cCI6MjA2MDQwNzE4OH0.ZJ_oFhQB2c5IIC8N_-IUTQt45i2xrRU5-SXSntPi2Ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);